---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package: name={{ docker_package }} state=present
  when: (ansible_os_family != 'Ubuntu') or (docker_version is undefined)

- name: Install Docker.
  apt:
    name: {{ docker_package }}={{ docker_version}}
    state: present
  when: ansible_os_family == 'Ubuntu') and (docker_version is defined)

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes

- include: docker-compose.yml
  when: docker_install_compose
